language: csharp
mono: none
dotnet: 2.1
os: linux
sudo: false
dist: trusty
addons:
  apt:
    sources:
    packages:
install:
script: 
  - dotnet restore opcpublisher
  - dotnet build -c Debug opcpublisher
  - dotnet build -c Release opcpublisher
