sudo: required
os: linux
dist: trusty
env:
  matrix:
    - build=default build_args=""
language: c
compiler: gcc
install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.1 -y
script: "bash bld/build.sh -c $build_args"
