language: csharp
dótnet: 2.0.0
sudo: required
dist: trusty
addons:
  apt:
    sources:
    packages:
install:
script: 
  - dotnet restore src
  - dotnet build -c Debug src
  - dotnet build -c Release src
