language: csharp
sudo: required
dist: trusty
addons:
  apt:
    sources:
    packages:
install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-2.0.0 -y
script: 
  - dotnet restore src
  - dotnet build -c Debug src
  - dotnet build -c Release src
