version: '3'
services:
  twinmodule:
    build: .
    restart: always
    network_mode: "${HOST_NETWORK:-host}"
    cap_add:
      - NET_ADMIN
    environment:
      - PCS_IOTHUB_CONNSTRING
  publishermodule:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-publisher:${IMAGE_VERSION:-latest}
    ports:
      - "62222:62222"
    restart: always
    environment:
      - _HUB_CS
    command: --aa
  opcserver0:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-ua-testing:${IMAGE_VERSION:-latest}
    hostname: opcserver0
    restart: always
    command: --sample -p 51210
    ports:
      - "51210:51210"
  opcserver1:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-ua-testing:${IMAGE_VERSION:-latest}
    hostname: opcserver1
    restart: always
    command: --sample -p 51211
    ports:
      - "51211:51211"
  opcserver2:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-ua-testing:${IMAGE_VERSION:-latest}
    hostname: opcserver2
    restart: always
    command: --sample -p 51212
    ports:
      - "51212:51212"
  opcserver3:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-ua-testing:${IMAGE_VERSION:-latest}
    hostname: opcserver3
    restart: always
    command: --sample -p 51213
    ports:
      - "51213:51213"
  opcserver4:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-ua-testing:${IMAGE_VERSION:-latest}
    hostname: opcserver4
    restart: always
    command: --sample -p 51214
    ports:
      - "51214:51214"
  opcserver5:
    image: ${REPOSITORY:-localhost:5000/azure-iiot-}opc-ua-testing:${IMAGE_VERSION:-latest}
    hostname: opcserver5
    restart: always
    command: --sample -p 51215
    ports:
      - "51215:51215"
