version: '3'
services:
  reverseproxy:
    build: ./reverse-proxy
    restart: always
    ports:
      - "10080:10080"
    depends_on:
      - registryservice
      - onboardingservice
      - gatewayservice
      - twinservice
  registryservice:
    build: 
      context: .
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.Registry/docker/Dockerfile
    ports:
      - "9042:9042"
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
  onboardingservice:
    build: 
      context: .
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.Onboarding/docker/Dockerfile
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_CONSUMERGROUP
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
  graphservice:
    build: 
      context: .
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.Graph/docker/Dockerfile
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
  twinservice:
    build: 
      context: .
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.Twin/docker/Dockerfile
    restart: always
    ports:
      - "9041:9041"
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
  historyservice:
    build: 
      context: .
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.History/docker/Dockerfile
    restart: always
    ports:
      - "9043:9043"
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
  gatewayservice:
    build: 
      context: .
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.Gateway/docker/Dockerfile
    ports:
      - "9040:9040"
      - "51111:51111"
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
