version: '3'
services:
  reverseproxy:
    build: ./services/reverse-proxy
    restart: always
    ports:
      - "10080:10080"
    depends_on:
      - registryservice
      - onboardingservice
      - gatewayservice
      - twinservice
      - twinwebui
      - twinmodule
  registryservice:
    build: 
      context: ./services
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.Registry/docker/Dockerfile
    ports:
      - "9042:9042"
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
  onboardingservice:
    build: 
      context: ./services
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.Onboarding/docker/Dockerfile
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_CONSUMERGROUP
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
  graphservice:
    build: 
      context: ./services
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.Graph/docker/Dockerfile
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
  twinservice:
    build: 
      context: ./services
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.Twin/docker/Dockerfile
    restart: always
    ports:
      - "9041:9041"
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
  historyservice:
    build: 
      context: ./services
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.History/docker/Dockerfile
    restart: always
    ports:
      - "9043:9043"
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
  gatewayservice:
    build: 
      context: ./services
      dockerfile: ./src/Microsoft.Azure.IIoT.Services.OpcUa.Gateway/docker/Dockerfile
    ports:
      - "9040:9040"
      - "51111:51111"
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
  twinwebui:
    build: ./samples/opc-twin-webui
    restart: always
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_PCS_AUTH_REQUIRED
      - REACT_APP_PCS_AUTH_ISSUER
      - REACT_APP_PCS_AUTH_AUDIENCE
      - REACT_APP_PCS_WEBUI_AUTH_AAD_APPID
      - REACT_APP_PCS_WEBUI_AUTH_AAD_AUTHORITY
      - REACT_APP_PCS_WEBUI_AUTH_AAD_TENANT
      - REACT_APP_PCS_TWIN_REGISTRY_URL=http://twinregistry:9042
      - REACT_APP_PCS_TWIN_SERVICE_URL=http://twinservice:9041
  twinmodule:
    build: ./modules/opc-twin
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
  twinmodule:
    build: ./modules/opc-publisher
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
    command: demo demo
  opcserver0:
    build: ./components/opc-ua
    hostname: opcserver0
    restart: always
    command: --sample -p 51210
  opcserver1:
    build: ./components/opc-ua
    hostname: opcserver1
    restart: always
    command: --sample -p 51211
  opcserver2:
    build: ./components/opc-ua
    hostname: opcserver2
    restart: always
    command: --sample -p 51212
  twinconsole:
    build: ./api
    command: exit
    environment:
      - PCS_TWIN_REGISTRY_URL=http://twinregistry:9042
      - PCS_TWIN_SERVICE_URL=http://twinservice:9041
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_WEBUI_AUTH_AAD_INSTANCE
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
