version: '3.4'

services:
  microsoft.azure.iiot.opcua.api.cli:
    image: ${DOCKER_REGISTRY}microsoftazureiiotopcuaapicli
    build:
      context: .
      dockerfile: OpcUa/Microsoft.Azure.IIoT.OpcUa.Api/cli/Dockerfile

  microsoft.azure.iiot.opcua.edge:
    image: ${DOCKER_REGISTRY}microsoftazureiiotopcuaedge
    build:
      context: .
      dockerfile: OpcUa/Microsoft.Azure.IIoT.OpcUa.Edge/src/Dockerfile


  microsoft.azure.iiot.opcua.registry:
    image: ${DOCKER_REGISTRY}microsoftazureiiotopcuaregistry
    build:
      context: .
      dockerfile: OpcUa/Microsoft.Azure.IIoT.OpcUa.Registry/src/Dockerfile


  microsoft.azure.iiot.opcua.twin:
    image: ${DOCKER_REGISTRY}microsoftazureiiotopcuatwin
    build:
      context: .
      dockerfile: OpcUa/Microsoft.Azure.IIoT.OpcUa.Twin/src/Dockerfile


  microsoft.azure.iiot.opcua.onboarding:
    image: ${DOCKER_REGISTRY}microsoftazureiiotopcuaonboarding
    build:
      context: .
      dockerfile: OpcUa/Microsoft.Azure.IIoT.OpcUa.Onboarding/src/Dockerfile


  microsoft.azure.iiot.opcua.services.cli:
    image: ${DOCKER_REGISTRY}microsoftazureiiotopcuaservicescli
    build:
      context: .
      dockerfile: OpcUa/Microsoft.Azure.IIoT.OpcUa.Services/Cli/Dockerfile

