version: '3'
services:
  twinregistry:
    build: 
      context: .
      dockerfile: ./src/Microsoft.Azure.IIoT.OpcUa.Services.Registry/docker/Dockerfile
    ports:
      - "9042:9042"
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_CORS_WHITELIST
  twinonboarding:
    build: 
      context: .
      dockerfile: ./src/Microsoft.Azure.IIoT.OpcUa.Services.Onboarding/docker/Dockerfile
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_CONSUMERGROUP
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
  twinservice:
    build: 
      context: .
      dockerfile: ./src/Microsoft.Azure.IIoT.OpcUa.Services.Twin/docker/Dockerfile
    restart: always
    ports:
      - "9041:9041"
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_CORS_WHITELIST
  twingateway:
    build: 
      context: .
      dockerfile: ./src/Microsoft.Azure.IIoT.OpcUa.Services.Gateway/docker/Dockerfile
    ports:
      - "9040:9040"
      - "51111:4840"
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_CORS_WHITELIST
