version: '3'
services:
  twinregistry:
    image: mcr.microsoft.com/iot/opc-twin-registry:latest
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET
  twinonboarding:
    image: mcr.microsoft.com/iot/opc-twin-onboarding:latest
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
  twinservice:
    image: mcr.microsoft.com/iot/opc-twin-service:latest
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET
  twinwebui:
    image: marcschier/azure-iiot-opc-twin-webui:latest
    restart: always
    command: npm start
  opcserver0:
    image: marcschier/azure-iiot-opc-twin:latest
    hostname: opcserver0
    restart: always
    command: --sample -p 51210
  opcserver1:
    image: marcschier/azure-iiot-opc-twin:latest
    hostname: opcserver1
    restart: always
    command: --sample -p 51211
  opcserver2:
    image: marcschier/azure-iiot-opc-twin:latest
    hostname: opcserver2
    restart: always
    command: --sample -p 51212
  twinmodule:
    image: marcschier/azure-iiot-opc-twin-module:latest
    command: --host demo twin
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
  reverseproxy:
    image: marcschier/azure-iiot-reverse-proxy:latest
    restart: always
    ports:
      - "8080:10080"
