version: '3'
services:
  reverseproxy:
    image: marcschier/azure-iiot-reverse-proxy:latest
    ports:
      - "8080:8080"
  twinregistry:
    image: marcschier/azure-iiot-opc-twin-registry:latest
    environment:
      PCS_IOTHUB_CONNSTRING:
      PCS_TELEMETRY_DOCUMENTDB_CONNSTRING:
      PCS_AUTH_ISSUER:
      PCS_AUTH_AUDIENCE:
      PCS_CORS_WHITELIST:
      PCS_APPLICATION_SECRET:
  twinonboarding:
    image: marcschier/azure-iiot-opc-twin-onboarding:latest
    environment:
      PCS_IOTHUB_CONNSTRING:
      PCS_IOTHUBREACT_HUB_ENDPOINT:
      PCS_IOTHUBREACT_HUB_PARTITIONS:
      PCS_IOTHUBREACT_HUB_NAME:
      PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT:
      PCS_IOTHUBREACT_AZUREBLOB_KEY:
      PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX:
  twinservice:
    image: marcschier/azure-iiot-opc-twin-service:latest
    environment:
      PCS_IOTHUB_CONNSTRING:
      PCS_TELEMETRY_DOCUMENTDB_CONNSTRING:
      PCS_AUTH_ISSUER:
      PCS_AUTH_AUDIENCE:
      PCS_CORS_WHITELIST:
      PCS_APPLICATION_SECRET:
  twinwebui:
    image: marcschier/azure-iiot-opc-twin-webui:latest
    command: npm start
  twinmodule:
    image: marcschier/azure-iiot-opc-twin-module:latest
    command: ["demo", "twin"]
    environment:
      PCS_IOTHUB_CONNSTRING:
  opcserver0:
    image: marcschier/azure-iiot-opc-twin:latest
    hostname: opcserver0
    command: ["--sample", "-p", "51210"]
  opcserver1:
    image: marcschier/azure-iiot-opc-twin:latest
    hostname: opcserver1
    command: ["--sample", "-p", "51211"]
  opcserver2:
    image: marcschier/azure-iiot-opc-twin:latest
    hostname: opcserver2
    command: ["--sample", "-p", "51212"]
