version: '3'
services:
  reverseproxy:
    image: nginx:1.13
    restart: always
    entrypoint: 
      - nginx 
      - -c 
      - /app/nginx.conf
    ports:
      - "443:10443"
    depends_on:
      - registryservice
      - gatewayservice
      - vaultservice
      - twinservice
      - historyservice
      - engineeringtool
      - jobsorchestrator
      - configurationservice
      - jobsservice
      - publisherservice
    volumes:
      - /app:/app:ro
      - /logs:/logs:rw
  engineeringtool:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/industrial-iot-frontend:${SERVICES_VERSION:-latest}
    restart: always
  jobsorchestrator:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/industrial-iot-jobs-orchestrator-service:${SERVICES_VERSION:-latest}
    restart: always
  configurationservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/industrial-iot-configuration-service:${SERVICES_VERSION:-latest}
    restart: always
  jobsservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/industrial-iot-jobs-service:${SERVICES_VERSION:-latest}
    restart: always
  publisherservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-publisher-service:${SERVICES_VERSION:-latest}
    restart: always
  vaultservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-vault-service:${SERVICES_VERSION:-latest}
    restart: always
  historyservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-history-service:${SERVICES_VERSION:-latest}
    restart: always
  registryservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com/iot/}opc-registry-service:${SERVICES_VERSION:-latest}
    restart: always
  twinservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com/iot/}opc-twin-service:${SERVICES_VERSION:-latest}
    restart: always
  gatewayservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com/iot/}opc-gateway-service:${SERVICES_VERSION:-latest}
    ports:
      - "4840:51111"
    restart: always
  onboardingservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com/iot/}opc-onboarding-service:${SERVICES_VERSION:-latest}
    restart: always
  jobsdispatcher:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com/iot/}opc-jobs-service:${SERVICES_VERSION:-latest}
    restart: always
  securityevents:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-alerting-service:${SERVICES_VERSION:-latest}
    restart: always
  modelprocessor:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-processor-service:${SERVICES_VERSION:-latest}
    restart: always
  registryevents:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/opc-registry-events-forwarder:${SERVICES_VERSION:-latest}
    restart: always
  fileuploadevents:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/industrial-iot-fileupload-forwarder:${SERVICES_VERSION:-latest}
    restart: always
  telemetryevents:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/industrial-iot-telemetry-processor:${SERVICES_VERSION:-latest}
    restart: always
  identityservice:
    image: ${SERVICES_REPOSITORY:-mcr.microsoft.com}/iot/industrial-iot-identity-service:${SERVICES_VERSION:-latest}
    restart: always
