version: '3'
services:
  reverseproxy:
    image: marcschier/azure-iiot-reverse-proxy:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - registryservice
      - onboardingservice
      - gatewayservice
      - twinservice
      - twinwebui
      - twinmodule
    volumes:
      - /app/certs:/app/certs:ro
  registryservice:
    image: marcschier/azure-iiot-opc-registry-service:latest
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
  onboardingservice:
    image: marcschier/azure-iiot-opc-onboarding-service:latest
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_CONSUMERGROUP
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
  twinservice:
    image: marcschier/azure-iiot-opc-twin-service:latest
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
  gatewayservice:
    image: marcschier/azure-iiot-opc-gateway-service:latest
    ports:
      - "51111:4840"
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
      - PCS_CORS_WHITELIST
  auth:
    image: azureiotpcs/pcs-auth-dotnet:1.0.0
    environment:
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER=${PCS_WEBUI_AUTH_AAD_AUTHORITY}/${PCS_WEBUI_AUTH_AAD_TENANT}
      - PCS_AUTH_AUDIENCE
      - PCS_APPLICATION_SECRET
      - PCS_CORS_WHITELIST
  twinwebui:
    image: marcschier/azure-iiot-opc-twin-webui:latest
    restart: always
    command: npm start
    environment:
      - PCS_AUTH_REQUIRED
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_WEBUI_AUTH_AAD_APPID
      - PCS_WEBUI_AUTH_AAD_AUTHORITY
      - PCS_WEBUI_AUTH_AAD_TENANT
  twinmodule:
    image: marcschier/azure-iiot-opc-twin-module:latest
    restart: always
    environment:
      - PCS_IOTHUB_CONNSTRING
    command: demo twin
  opcserver0:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    hostname: opcserver0
    restart: always
    command: --sample -p 51210
  opcserver1:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    hostname: opcserver1
    restart: always
    command: --sample -p 51211
  opcserver2:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    hostname: opcserver2
    restart: always
    command: --sample -p 51212
